wordBank = ['abort', 'acorn', 'actor', 'aloof', 'again', 'agony', 'ahead', 'alive', 'alley', 'awash', 'abuzz', 'amino', 'altar', 'abyss',
'being', 'board', 'brand', 'bacon', 'bless', 'brain', 'barge', 'black', 'bleak', 'bloom', 'basin', 'bulky', 'bluff', 'boxer',
'cited', 'civil', 'crave', 'carol', 'cheek', 'chore', 'carve', 'crazy', 'choke', 'close', 'chaos', 'chuck', 'chalk', 'curry',
'douse', 'drown', 'drape', 'delve', 'dying', 'dress', 'dream', 'decoy', 'dozen', 'drama', 'dodge', 'defer', 'dwell', 'diode',
'evade', 'event', 'evict', 'evoke', 'essay', 'erupt', 'error', 'erase', 'equip', 'enemy', 'exist', 'ensue', 'eerie', 'exude',
'fever', 'fresh', 'fancy', 'fiend', 'fired', 'feast', 'facet', 'false', 'foray', 'forge', 'fjord', 'flora', 'flint', 'flute',
'grind', 'guilt', 'grill', 'great', 'gorge', 'genie', 'group', 'grade', 'grave', 'grief', 'guest', 'gauge', 'graft', 'genus',
'habit', 'happy', 'handy', 'harsh', 'hatch', 'helix', 'hedge', 'hello', 'heard', 'horse', 'hijab', 'hydro', 'humus', 'henna',
'ideal', 'image', 'irate', 'issue', 'inbox', 'index', 'idiot', 'imply', 'input', 'inner', 'islet', 'igloo', 'inapt', 'incus',
'jelly', 'jewel', 'joint', 'judge', 'juice', 'juicy', 'joked', 'jerky', 'joker', 'juked', 'jumpy', 'joule', 'jingo', 'jumbo',
'knife', 'knock', 'known', 'kabob', 'khaki', 'knead', 'kooky', 'kazoo', 'karat', 'kayak', 'kudos', 'kiddo', 'klick', 'knurl',
'lease', 'least', 'label', 'lover', 'laced', 'lousy', 'latex', 'livid', 'lemon', 'lever', 'laden', 'lyric', 'lunar', 'lucid',
'minor', 'major', 'meant', 'miner', 'medal', 'motor', 'mercy', 'mount', 'moral', 'movie', 'merit', 'mixer', 'macho', 'mogul',
'nylon', 'nurse', 'noose', 'novel', 'named', 'nomad', 'night', 'naval', 'nymph', 'nicer', 'nosey', 'nevus', 'nexus', 'ninja',
'onset', 'opera', 'optic', 'orbit', 'ocean', 'occur', 'offer', 'often', 'other', 'older', 'opium', 'orate', 'ombre', 'owlet',
'paste', 'pasta', 'plaid', 'plane', 'pilot', 'place', 'price', 'parch', 'panda', 'pinch', 'pzazz', 'piano', 'petty', 'photo',
'queen', 'query', 'quest', 'queue', 'quick', 'quiet', 'quilt', 'quite', 'quote', 'qualm', 'quell', 'quack', 'quant', 'quill',
'radio', 'rover', 'radar', 'rally', 'reach', 'ranch', 'react', 'rainy', 'realm', 'rebel', 'reply', 'ratio', 'rhyme', 'recap',
'snake', 'stale', 'slate', 'squid', 'sound', 'scale', 'shade', 'snare', 'safer', 'short', 'sixth', 'solve', 'salad', 'swept',
'title', 'torso', 'trend', 'tamer', 'taper', 'tease', 'token', 'terse', 'trope', 'timer', 'toast', 'trust', 'tract', 'tutor',
'urban', 'usage', 'under', 'urged', 'upper', 'until', 'unity', 'upset', 'uncle', 'union', 'unzip', 'unary', 'uvula', 'unify',
'vague', 'valid', 'value', 'vapor', 'vault', 'venue', 'viral', 'visit', 'vital', 'voice', 'vexed', 'vegan', 'valet', 'vodka',
'witch', 'watch', 'width', 'world', 'worry', 'worse', 'woman', 'which', 'while', 'whose', 'whirl', 'wrung', 'wordy', 'whist',
'xenon', 'xerox', 'xylem', 
'yacht', 'yeast', 'yield', 'young', 'youth', 'yummy', 'yucky', 'yawed', 'yoked', 'yearn', 'yucca', 'yodel', 'yahoo', 'yapok',
'zesty', 'zippy', 'zilch', 'zebra', 'zonal'
]
